Repository goblint/cil, pull requests merged in 2021-12, with the labels that each got.

#52 RFC: Remove support for MSVC
  CHANGES
  Makefile.in
  config.mk.in
  configure
  configure.ac
  lib/perl5/App/Cilly.pm.in
  lib/perl5/patcher
  src/cfg.ml
  src/check.ml
  src/cil.ml
  src/cil.mli
  src/ciloptions.ml
  src/dataflow.ml
  src/ext/liveness/usedef.ml
  src/ext/pta/ptranal.ml
  src/ext/syntacticsearch/funcVar.ml
  src/ext/zrapp/zrapp.ml
  src/formatparse.mly
  src/frontc/cabs.ml
  src/frontc/cabs2cil.ml
  src/frontc/cabshelper.ml
  src/frontc/cabsvisit.ml
  src/frontc/clexer.mll
  src/frontc/cparser.mly
  src/frontc/cprint.ml
  src/frontc/frontc.ml
  src/frontc/frontc.mli
  src/machdep-ml.c.in
  src/mergecil.ml
  src/rmtmps.ml
  test/Makefile.msvc
  test/small1/attr.c
  test/small1/msvc2.c
  test/small1/msvc3.c
  test/small1/msvc4.c
  test/small1/msvc6.c
  test/small1/msvc7.c
  test/small1/msvc8.c
  test/small1/msvc9.c
  test/small1/vararg11.c
  test/small1/wchar-bad.c
  test/small2/hashtest.c
  test/small2/hufftest.c
  test/small2/rbtest.c
  test/small2/testbtree.c
  test/small2/wes-hashtest.c
  test/small2/wes-rbtest.c
  test/test-bad
  test/testcil.pl
Labels: cleanup

#53 Use `Cilint` in `CInt64`
  .merlin
  src/check.ml
  src/cil.ml
  src/cil.mli
  src/cilint.ml
  src/cilint.mli
  src/ext/zrapp/rmciltmps.ml
  src/formatparse.mly
  src/frontc/cabs2cil.ml
  src/mergecil.ml
Labels: cleanup

#56 Change some errors to warnings for coreutils
  src/frontc/cabs2cil.ml
  src/frontc/cabshelper.ml
Labels: bug

#48 Add C11 generic support
  CHANGES
  Makefile.in
  doc/cil.tex
  src/check.ml
  src/cil.ml
  src/cil.mli
  src/frontc/cabs.ml
  src/frontc/cabs2cil.ml
  src/frontc/cabsvisit.ml
  src/frontc/clexer.mll
  src/frontc/cparser.mly
  src/frontc/cprint.ml
  src/machdep-ml.c.in
  src/machdepenv.ml
  src/mergecil.ml
  test/Makefile
  test/small1/c11-generic.c
  test/small1/clang-c11-generic-1-1.c
  test/small1/clang-c11-generic-1-2.c
  test/small1/clang-c11-generic-2.c
  test/small1/decl1.c
  test/small1/gcc-c11-generic-1.c
  test/small1/gcc-c11-generic-2-1.c
  test/small1/gcc-c11-generic-2-2.c
  test/small1/gcc-c11-generic-2-3.c
  test/small1/gcc-c11-generic-2-4.c
  test/small1/gcc-c11-generic-2-5.c
  test/small1/gcc-c11-generic-2-6.c
  test/small1/gcc-c11-generic-2-7.c
  test/small1/gcc-c11-generic-3-1.c
  test/small1/gcc-c11-generic-3-2.c
  test/small1/gcc-c11-generic-3-3.c
  test/small1/gcc-c11-generic-3-4.c
  test/testcil.pl
Labels: enhancement

#59 Make constFold aware of overflows and prevent constant folding on overflows
  src/cil.ml
  src/cil.mli
  src/frontc/cabs2cil.ml
Labels: enhancement
