Repository goblint/cil, pull requests merged in 2022-07, with the labels that each got.

#103 Add option `removeBranchingOnConstants`
  src/cil.ml
  src/cil.mli
  src/frontc/cabs2cil.ml
Labels: enhancement

#104 Port entire build process from configure/make to dune
  .github/workflows/docs.yml
  .github/workflows/tests.yml
  .gitignore
  .merlin
  Makefile.in
  README.md
  _tags
  aclocal.m4
  bin/dune
  bin/realGccConfigure.ml
  cil.odocl
  config.guess
  config.h.in
  config.mk.in
  config.sub
  configure
  configure.ac
  doc/_tags
  doc/cil.tex
  doc/dune
  doc/html/cil/dune
  doc/html/cil/header.html
  doc/html/cil/index.html
  dune
  dune-project
  goblint-cil.opam
  install-sh
  lib/perl5/App/Cilly.pm.in
  lib/perl5/App/Cilly/CilConfig.pm.in
  lib/perl5/App/Cilly/dune
  lib/perl5/App/dune
  m4/cil.m4
  m4/ocaml.m4
  myocamlbuild.ml
  src/_tags
  src/cil.ml
  src/cil.mli
  src/cil.mllib
  src/cilversion.ml
  src/cilversion.ml.in
  src/dune
  src/machdep-ml.c
  src/machdep.cppo.ml
  src/machdepConfigure.ml
  stamp-h.in
  test/Makefile
  test/dune
Labels: cleanup, setup

#105 Reenable some OCaml warnings
  src/check.ml
  src/cil.ml
  src/cilint.ml
  src/dune
  src/ext/pta/golf.ml
  src/ext/pta/olf.ml
  src/ext/pta/ptranal.ml
  src/ext/pta/steensgaard.ml
  src/ext/zrapp/zrapp.ml
  src/formatparse.mly
  src/frontc/cabs2cil.ml
  src/frontc/cabsvisit.ml
  src/frontc/clexer.mll
  src/frontc/cparser.mly
  src/frontc/whitetrack.ml
  src/ocamlutil/clist.ml
  src/ocamlutil/errormsg.ml
  src/ocamlutil/growArray.ml
  src/ocamlutil/pretty.ml
  src/ocamlutil/stats.ml
  src/rmtmps.ml
Labels: cleanup

#106 Remove batteries dependency to support OCaml 5
  .github/workflows/tests.yml
  dune-project
  goblint-cil.opam
  src/dune
  src/ext/syntacticsearch/dune
  src/ext/syntacticsearch/funcDatatype.ml
  src/ext/syntacticsearch/funcFunction.ml
  src/ext/syntacticsearch/funcVar.ml
  src/ocamlutil/util.ml
  src/ocamlutil/util.mli
Labels: setup

#108 Support for `_Alignas(...)`
  src/frontc/clexer.mll
  src/frontc/cparser.mly
  test/small1/alignas.c
  test/testcil.pl
Labels: enhancement, c11

#109 Allow casts from any type to `void`
  src/frontc/cabs2cil.ml
  test/small1/c99-tgmath2.c
  test/testcil.pl
Labels: bug
