Repository goblint/cil, pull requests merged in 2022-11, with the labels that each got.

#121 Expose `populateLabelAlphaTable`
  src/cil.ml
  src/cil.mli
Labels: enhancement

#123 Only constant fold for `shitfleft` when defined
  src/cil.ml
  test/small1/constfold2.c
  test/testcil.pl
Labels: bug, enhancement

#125 Make more loop statement locations synthetic
  src/frontc/cabs2cil.ml
Labels: bug, cleanup

#124 Fix merging and renaming of inlines
  README.md
  doc/cil.tex
  lib/perl5/App/Cilly.pm.in
  lib/perl5/patcher
  src/cil.ml
  src/cil.mli
  src/ciloptions.ml
  src/cilutil.ml
  src/main.ml
  src/mergecil.ml
  test/Makefile
  test/small1/combine-c99-mergeinline1_1.c
  test/small1/combine-c99-mergeinline1_2.c
  test/small1/combine-c99-mergeinline2_1.c
  test/small1/combine-c99-mergeinline2_2.c
  test/small1/combine-c99-mergeinline3_1.c
  test/small1/combine-c99-mergeinline3_2.c
  test/small1/combine-c99-mergeinline4_1.c
  test/small1/combine-c99-mergeinline4_2.c
  test/small1/combine-c99-mergeinline5_1.c
  test/small1/combine-c99-mergeinline5_2.c
  test/small1/combine-c99-mergeinline6_1.c
  test/small1/combine-c99-mergeinline6_2.c
  test/small1/combine-c99-mergeinline7.h
  test/small1/combine-c99-mergeinline7_1.c
  test/small1/combine-c99-mergeinline7_2.c
  test/small1/combine-c99inline1_1.c
  test/small1/combine-c99inline1_2.c
  test/small1/combine-c99inline2_1.c
  test/small1/combine-c99inline2_2.c
  test/small1/combine-c99inline3_1.c
  test/small1/combine-c99inline3_2.c
  test/small1/combine-c99inline4_1.c
  test/small1/combine-c99inline4_2.c
  test/small1/combine-c99inline5_1.c
  test/small1/combine-c99inline5_2.c
  test/small1/combine-c99inline6_1.c
  test/small1/combine-c99inline6_2.c
  test/small1/combine-c99inline7_1.c
  test/small1/combine-c99inline7_2.c
  test/small1/combine-c99inline7_3.c
  test/small1/combine-c99inline8_1.c
  test/small1/combine-c99inline8_2.c
  test/small1/combine-c99inline8_3.c
  test/small1/combine-c99inline9.h
  test/small1/combine-c99inline9_1.c
  test/small1/combine-c99inline9_2.c
  test/small1/combine-c99inline_2.c
  test/small1/combinemerge1_1.c
  test/small1/combinemerge1_2.c
  test/small1/combinemerge1_3.c
  test/testcil.pl
Labels: bug, c99, c11
