Repository goblint/cil, pull requests merged in 2023-02, with the labels that each got.

#129 Add `return` statements in `noreturn` functions
  src/cil.ml
  src/cil.mli
  src/frontc/cabs2cil.ml
Labels: enhancement, student-job

#130 Respect C11 `_Alignas(...)` for computing alignments
  src/frontc/cparser.mly
  test/small1/alignas_proper.c
  test/testcil.pl
Labels: bug, c11

#119 Add support on machines where long double and float128 do not have the same size
  src/cil.ml
  src/cil.mli
  src/frontc/cabs2cil.ml
  src/frontc/clexer.mll
  src/machdep-ml.c
  src/machdep.cppo.ml
  src/machdepenv.ml
  test/small1/float3.c
  test/testcil.pl
Labels: enhancement

#133 Fix `Pretty` not resetting all global state between calls
  src/ocamlutil/pretty.ml
Labels: bug
