Repository goblint/cil, pull requests merged in 2023-10, with the labels that each got.

#155 Add attribute `goblint_cil_nested` to local `varinfo`s that are not declared at top scope
  src/frontc/cabs2cil.ml
  src/frontc/cabs2cil.mli
Labels: enhancement

#157 Ignore top level qualifiers in `__builtin_types_compatible_p`
  src/frontc/cabs2cil.ml
  test/small1/builtin6.c
  test/testcil.pl
Labels: bug

#156 Add option `silenceLongDoubleWarning`
  src/frontc/cabs2cil.ml
  src/frontc/cabs2cil.mli
Labels: enhancement, cleanup
